title: Devan Craig # your name (or website title) here
logo: "https://media-exp1.licdn.com/dms/image/C5603AQFC-1ccKO185Q/profile-displayphoto-shrink_200_200/0/1607556795271?e=1613001600&v=beta&t=uqJ3IAdSHF4UsqB2bB1M5E39TGxI-FF-gcZhx2kcAXE" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  "Experience is the name everyone gives to their mistakes." – Oscar Wilde 
  <br><br>
  <a href="https://www.linkedin.com/in/devan-craig-67b55a124/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
