theme: jekyll-theme-slate
title: Devan Craig
subtitle: Experience is the name everyone gives to their mistakes. – Oscar Wilde
Description: Describes my current experience and projects that I've done.
