title: Devan Craig # your name (or website title) here
logo: "profile.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  "Experience is the name everyone gives to their mistakes." – Oscar Wilde 
  <br><br>
  <a href="https://www.linkedin.com/in/devan-craig-67b55a124/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
